### ISSUE TITLE
Web-view design

### ISSUE THREAD

**Issue by dingsheng-ong** [aimlac-7564616D/web-view#1]
**Light Theme**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21995492/154249955-506904fe-6e59-430d-8254-e84905e0aadf.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21995492/154250087-8e7584ee-6c5a-4e0d-974d-27ab4314d744.png">

**Dark Theme:**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21995492/154249848-dca0406d-d8db-4228-a8a9-b94eacb4fea9.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21995492/154250321-dae7195c-a85b-49e2-8c3c-3c3d84e2b596.png">

**Comment by fjebaker** [comment]
These look gorgeous! Are they wireframes, or have you already an implementation?

**Comment by dingsheng-ong** [comment]
> These look gorgeous! Are they wireframes, or have you already an implementation?

Thanks! They're written in Flask + HTML.
